### ISSUE TITLE
2.3.1 hangs at exit

### ISSUE THREAD

**Issue by MatthiasJ1** [bernhard-42/vscode-ocp-cad-viewer#73] opened 2024-04-23 23:10 UTC
Pip package version: 2.3.1
vsCode extension version: v2.3.1

If I run the following file in vsCode:

```py
import ocp_vscode
ocp_vscode.show()
print("Hello")
```

it will hang indefinitely. If you then press Ctrl-C:

```
Hello
^CException ignored in: <module 'threading' from '/opt/homebrew/Caskroom/micromamba/envs/cad/lib/python3.12/threading.py'>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/micromamba/envs/cad/lib/python3.12/threading.py", line 1622, in _shutdown
    lock.acquire()
```

**Comment by MatthiasJ1** [comment] 2024-04-24 00:07
This may or may not be related but this computer did not have the Jupyter vsCode extension installed, although this was not an issue in 2.2.2

**Comment by bernhard-42** [comment] 2024-04-24 06:09
I saw this when running the unit tests, but it didn't happen when running in VSCode.
I'll try to reproduce

**Comment by bernhard-42** [comment] 2024-04-24 06:35
Found the problem.
I remove closing websockets after each call (saves up to a second).
However, is a big issue at the end. Need to see what I can do.
Uncomment the following lines and it should behave like before:

https://github.com/bernhard-42/vscode-ocp-cad-viewer/blob/b6182c681ad86166aa6f320793ff668e1fc1f2d5/ocp_vscode/comms.py#L145-L148

**Comment by bernhard-42** [comment] 2024-04-24 07:02
For reference 
https://github.com/python-websockets/websockets/issues/1455

**Comment by MatthiasJ1** [comment] 2024-04-24 07:44
This feels like a hack but it may solve the issue: https://docs.python.org/3/library/atexit.html

**Comment by bernhard-42** [comment] 2024-04-24 13:46
I'll start with trying to fix the thread thing as mentioned above. But if that doesnt work, atexit is a good next step 😀

**Comment by bernhard-42** [comment] 2024-04-24 17:29
`pip install --upgrade git+https://github.com/python-websockets/websockets.git@f0398141d2efd28f64d8e1d6d9adc179a9e5e334`
This commit (from last week) fixes the issue. Need to check whether websockets 12.0 is compatible. But this would be the easiest fix

btw. `atexit` fails, since the program is waiting for the thread => no exit happens 😀

**Comment by bernhard-42** [comment] 2024-04-24 17:41
@MatthiasJ1 Could you maybe try the the pip installation of websockets on your machine? pip will complain tht ocp_vscode wants websockets 11, but that can be ignored.
For me it solves the problem

**Comment by MatthiasJ1** [comment] 2024-04-25 03:40
Installing the latest released version does not fix the issue but installing the dev version from github does fix it.

**Comment by bernhard-42** [comment] 2024-04-25 16:15
arrg, pypi doesn't allow direct links as dependencies. So, can't package this simple fix. Need to find another way

**Closed** 2024-05-04 12:18 UTC
Labels: bug

**Comment by MatthiasJ1** [comment] 2024-05-08 07:45
Sorry for the late reply, just confirming that it is fixed for me. Thanks for looking into this.
